- config.v
- vid.v
- view.v
- zquery.v
Add a new config structure. This structure could then be used to load user config files into vid (Colors, text size, tab type, etc ...).
Dark mode option :
> config structure and dark mode

- vid.v
You can move with arrow keys in Normal and Insert modes.
> moving with arrow keys

- vid.v
remove glm and rand imports from vid.v
> remove unused imports

- timer.v
- vid.v
- view.v
Prepare for https://github.com/vlang/v/pull/2774
> Prepare for os.mkdir being ?bool. More robust os.read_lines usage.

- vid.v
Now command with one option like `vid -dark`, `vid -window` works.
> Respect arguments start with hyphen('-')

- vid.v
- view.v
Enables green tests at https://github.com/vlang/v/pull/2941 on MacOSX .
> Fix building vid with v at PR #2941 .

- timer.v
- vid.v
- view.v
The current code will make the V compiler complain.
This PR addresses all V errors that the compiler pointed out.
Note that I did not test that this code compiles in C as includes are not working correctly.
> vid: Fix V errors

- config.v
- timer.v
- vid.v
- view.v
This PR fixes vid compilation with recent V.
> Fix compilation with V 0.1.26 50a8373.e5ae4b6

- config.v
- timer.v
- uiold/ui_darwin.c.v
- uiold/ui_linux.c.v
- uiold/ui_windows.c.v
- vid.v
- view.v
- zquery.v
With this PR, vid compiles cleanly without warnings with latest V.
> update: compile with V 0.1.27 4af4a8f

- vid.v
This fixes some error messages when stricter type checking is active.
> types: prepare for stricter type checking

- vid.v
This PR cleans up event handling in vid. It also fixes a bug where in insert mode, updates were not visible until you exited insert mode.
> vid: refresh on any event

- ved.v
This fixes startup of ved on linux after v's 3a8be4d commit.
> fixes due to os.home_dir no longer returning a path with a trailing slash

- .gitignore
- config.v
- query.v
- uiold/ui_darwin.c.v
- uiold/ui_linux.c.v
- uiold/ui_windows.c.v
- ved.v
- view.v
I also ran vfmt where possible.
> fix syntax warnings about fn arg types

- .github/workflows/ci.yml
- .gitignore
- README.md
- uiold/ui_windows.c.v
The macos CI fails due to the same reason as V UI workflow.
> create GH Actions CI workflow

- .github/FUNDING.yml
- README.md
- copy the FUNDING.yml from main repo
**readme:**
- wrap the lines to a maximum length of 100
- cleanup the links
- remove the section `Support the development`
> readme: cleanup; create FUNDING.yml

- query.v
- ved.v
- view.v
Needed for https://github.com/vlang/v/pull/7886
> fix build with latest V

- .github/workflows/ci.yml
- uiold/ui_darwin.c.v
- ved.v
Depends on https://github.com/vlang/v/pull/9711
> format files and enable vet step in CI

- ved.v
- view.v
Needs to be tested. It compiles but I can't test the UI.
> replace ustring with runes

- ved.v
- view.v
Needed to fix compilation with V after
https://github.com/vlang/v/pull/11050
> fix ved compilation, after `Time.unix` becomes i64

- README.md
Appends Arch freetype installation instructions to the pre-existing list.
> + add Arch freetype installation instructions

- query.v
- ved.v
This PR makes ved easier to run for windows users.
> Add [console] to main, run vfmt

- v.mod
Just noticed this while looking around.
> Fix the repo url

- welcome.txt
> Add binding C q to welcome file

- .gitignore
- query.v
- ved.v
- view.v
Fixes:
* [Use Cmd for quitting](https://github.com/vlang/ved/pull/152/commits/ffc1746133bc77bc37717425c2367680f8213ae7)
* [FIX: avoid index out of range during find](https://github.com/vlang/ved/pull/152/commits/c2ea8ad79ff58731afa2529828284b8a7b236040)
* [FIX: enable the use of ctrlp outside git repo](https://github.com/vlang/ved/pull/152/commits/87cbbebec3952e64703c51197f9022ddb1326ac0)
* [FIX: when changing files goto line 0](https://github.com/vlang/ved/pull/152/commits/b28ec142cfb2b5245dc50eaa50606a07abc50419)
Sorry if this is kind of messy.
> Multiple quick fixes

- v.syntax
- ved.v
- view.v
Hi! This PR adds several capabilities to the editor. I have also edited some of the basic config (basically just go up on delete) to make it more first-time-user friendly, though I would be happy to remove those edits. Here's what the PR adds:
- Different cursors for different modes (default for normal, tall bar for insert, two bars for visual)
- Titlebar indicator for visual mode
- Rough scrolling support
- Rough mouse support
- `-laptop` arg now accessible no matter screen size
- Movement issues are fixed
- Unable to reach the end of a line via the right arrow key/l
- The first line would be hidden behind the titlebar when scrolling/moving to the top without `gg`
I have also changed the code to read the v keys (for syntax highlighting) from a text file. This is the first step on a …
> Better cursor, scrolling and mouse support

- ved.v
That PR introduces stricter type compatibility checks for pointers.
> prepare for V PR#16783

- timer.v
- Fix #165, fix naming to prevent import symbol shadowing.
> Fix naming to prevent shadowing

- timer.v
This PR is part of https://github.com/vlang/v/pull/17210, which fix naming in order to satisfies forbiding symbol shadowing.
> Fix varaible naming

- config.v
- query.v
- timer.v
- ved.v
for green CI
https://github.com/vlang/v/pull/20201
> replace string.last_index() to string.index_last()

- timer.v
- ved.v
> fix timer.v

- .github/workflows/ci.yml
- autocomplete.v
- query.v
- timer.v
- ved.v
After https://github.com/vlang/v/pull/21293
> use unix() method to access unix times

- ved.v
This would make a required change in conjunction with https://github.com/vlang/v/pull/21566
> specify `mut` when passing mutated buffer arg 
